dockerfile: |-
  RUN apk add --no-cache yaml-dev build-base git openssl-dev
  RUN gem install gem_hadar

script: &script |-
  echo -e "\e[1m"
  ruby -v
  echo -e "\e[0m"
  bundle update --all
  bundle install
  bundle exec rake spec

fail_fast: yes

images:
  ruby:4.0-alpine: *script
  ruby:3.4-alpine: *script
  ruby:3.3-alpine: *script
  ruby:3.2-alpine: *script
