development: &development
  styles:
    'timestamp': [ yellow, bold ]
    'file': [ blue, bold ]
    severity:
      debug: green
      info: green
      warn:  yellow
      error: red
      fatal: [ red, blink ]
      unknown: red
  formats:
    default: &default_format >
      {%lt%timestamp} {%5s%severity}
      "{%0.<%= ENV.fetch('COLUMNS', 80).to_i / 2 %>%message}"
      {location}
      {file}{-%O%backtrace}{-%O%meta}
    d: *default_format
    long: &long_format |
      timestamp: {%lt%timestamp}
      severity: {severity}
      message: "{message}"
      metric: {metric} {value} {type}
      error_class: {error_class}
      backtrace: {%O%backtrace}
      location: {location}
      file: {file}
      meta: {%O%meta}\n
    l: *long_format
    legacy: >
      {%0.1s%severity} [{%lt%timestamp} #{%d%pid}] {%5s%severity} --
      {program}: {message}
    metric: >
      {%ft%timestamp} {metric} {value} {type}
  config_files:
    rails:
      - log/development.log
    test:
      - log/test.log
    redis:
      - /usr/local/var/log/redis.log
    elasticsearch:
      - /usr/local/var/log/elasticsearch.log
  legacy_supported: yes
test: *development
staging: *development
production: *development
